title: Carlos.Ling
description: 技术思考与工程实践
url: "https://zishaha.github.io"
baseurl: "/blog"
author: Carlos Ling
lang: zh-CN

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - README.md
  - plan.md
  - Gemfile
  - Gemfile.lock
